### PR TITLE
Node-hc should return same rc as child process

### LINKED ISSUE #363: node-hc returns 0 exit code on failure
The `node-hc` script (a.k.a. [bin/appmetrics-cli.js](https://github.com/RuntimeTools/appmetrics/blob/master/bin/appmetrics-cli.js)) returns 0 even if an error was thrown, ideally it would pass back node's return code on exit.

```bash
echo 'throw "SomeError"' >test.js
node-hc test.js
echo $?                                                 # Returns 0
node test.js
echo $?                                                 # Returns 1
```

This is also the case if appmetrics wasn't installed properly (i.e. if appmetrics failed to initialise because a dependency didn't install properly).

### PR DESCRIPTION
**Pull request by sjanuary**
fixes  #363
also need to add a test for this

### CODE REVIEW

File: bin/appmetrics-cli.js [hunk 1]
```diff
@@ -49,3 +49,7 @@ if (process.env.NODE_PATH) {
 }
 
 var p = child_process.fork(launcher_filename, args, {"execArgv": node_args})
+
+p.on('close', (code) => {
```
Comment (sam-github) [inline bin/appmetrics-cli.js]: This will work if the child process exits, but if it terminates with signal, the cli will exit with `0`.

```
on('close', (code, signal) => {
  if(signal) {
    process.kill(process.pid, signal);
  } else {
    process.exit(code);
  }
});
```
might work better

Comment (sjanuary) [inline bin/appmetrics-cli.js]: Thanks @sam-github, I'll make that change.

Comment (sjanuary) [inline bin/appmetrics-cli.js]: PR updated

**Comment by gibfahn** [comment]
FYI if you add a `Fixes: https://github.com/RuntimeTools/appmetrics/issues/363` line to your commit message, when you land this it will automatically close the issue.

**Comment by sjanuary** [comment]
@gibfahn - "Fixes" with a capital F?  I used "fixes #363", does that not work?

**Comment by tobespc** [comment]
LGTM

**Comment by sjanuary** [comment]
@tobespc - I think you closed this instead of merging by accident

**Comment by tobespc** [comment]
lgtm

**Comment by gibfahn** [comment]
@sjanuary did you ever get round to adding a test for this?
